# Commands to start on workspace startup
tasks:
  - init: docker compose up -d --build
    command: docker compose up
# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview
